version: 2

before:
  hooks:
    - cd server && go mod tidy
    - cd server && go generate ./...

builds:
  - id: grql
    main: ./server/cmd/server
    binary: grql
    dir: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: grql
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Code Refactoring'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: cedricziel
    name: grql
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  header: |
    ## What's Changed
  footer: |
    ## Docker Images
    
    ```bash
    docker pull ghcr.io/cedricziel/grql:{{ .Tag }}
    ```
    
    ## Installation
    
    ### Homebrew (macOS/Linux)
    ```bash
    brew tap cedricziel/tap
    brew install grql
    ```
    
    ### Download Binary
    Download the appropriate binary for your platform from the assets below.

dockers:
  - id: grql
    image_templates:
      - "ghcr.io/cedricziel/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/cedricziel/{{ .ProjectName }}:v{{ .Major }}"
      - "ghcr.io/cedricziel/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/cedricziel/{{ .ProjectName }}:latest"
    dockerfile: server/Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

brews:
  - repository:
      owner: cedricziel
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/cedricziel/grql
    description: "Unified query language frontend for Grafana Mimir, Loki, and Tempo"
    license: "MIT"
    test: |
      system "#{bin}/grql", "--version"
    dependencies:
      - name: go
        type: optional

nfpms:
  - id: grql
    package_name: grql
    vendor: Cedric Ziel
    homepage: https://github.com/cedricziel/grql
    maintainer: Cedric Ziel <cedric@ziel.one>
    description: "Unified query language frontend for Grafana Mimir, Loki, and Tempo"
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    section: default
    priority: extra